### ISSUE TITLE
can't type 唔 after typing m

### ISSUE THREAD

**Issue by miklcct** [fcitx/libime-jyutping#12]
fcitx5-jyutping does not show `唔` when I type `m`, and it doesn't show all characters with pronunciation ng when I type `ng`.

**Comment by wengxt** [comment]
![图片](https://github.com/fcitx/libime-jyutping/assets/259684/54438cf1-f0b2-4df4-8c17-790730ee3f35)
It's there, unfortunately, due to the not so ideal model frequency (to be honest, the model is not really based on Cantonese text but just some traditional Chinese text) , it is at the quite later position in the list

ng is in a similar situation

**Comment by wengxt** [comment]
There's one thing we can fix regardless of model, which is the fuzzy score should be zero for "m" and "ng". which should move them closer to the start of candidate lists.

**Comment by wengxt** [comment]
![图片](https://github.com/fcitx/libime-jyutping/assets/259684/85232ea9-9843-4796-a273-2609733a002b)
hopefully it's much improved by now
